swapagarwal/awesome-inspiration

- README.md
> Songs: Use tabular format

- README.md
* Added inspirational quote from Jimmy Dean
* Fixed dead images for others in Quotes section
> added inspirational quote from Jimmy Dean

- README.md
This program connects entrepreneurs from 54 African countries to benefit from the TEFT 100 million dollars grant for entrepreneurs.
> Added 2 inspiring videos from Tony Eleumelu Foundation Oct 13/14,2017 

- README.md
Addresses #13  
Added inspirational  Rock songs. 🎸 🥁 🤘
> Add Rock songs

- README.md
> added a vid

- README.md
Thanks for the opportunity to contribute. Added the remixed version of "This is Me" from The Greatest Showman.
> Added an inspirational song

- README.md
added one song in motivational song category 'Macklemore "WINGS" ' as this song is close to my heart and inspires me to get up and work.!
> add motivational song 'Macklemore "WINGS" '

- README.md
Rose never propagandize its fragnant, but its own fragnant spreads throught its surrounding. - Ir. Soekarno
> [ADD] Soekarno Quote

- README.md
Hey, @swapagarwal. I am learning about OpenSource and I came upon your repository and thought about adding a few items in your list. Hope it works well with you. Thanks for the opportunity.
> Added some inspiring books in the list

- README.md
This is a quote on Jurgen Klopp losing 6 Champions league finals.
> Quote by Jurgen Klopp

- README.md
Added Señorita by Shawn Mendes, Camila Cabello
> Added new song

- README.md
Added a new inspirational song  and a new inspirational quote
> Updated the file README.md

- README.md
> Ecclesiates 9:10 quote

- README.md
> added-inspirational-quote

- README.md
added a post...love to do more
> added a post

- README.md
Added "Try Everything" to Songs list #13
> Added "Try Everything" to Songs list

- README.md
I added a quote by Keanu Reeves under the inspirational quotes area.
> Added inspirational Keanu Reeves quote

- README.md
This post talks about the positive thinking
> add a new post about positive thinking

- README.md
I added the following Helen Keller quote to the README file: "Life is either a daring adventure or nothing at all."
> Added Helen Keller quote to README

- README.md
added song by NEFFEX called Make Moves
> added song by NEFFEX called Make Moves

- README.md
> add song lyrics and Youtube video link

- README.md
"Good students find questions, not answers" by Daniel Lemire
> Added post which incredibly helped me as a student

- README.md
Hacktoberfest 2020 contribution
> Added new song 

- README.md
Added a quote and picture. 
Thanks!
> added a quote from Steve jobs.

- README.md
Hi, I added movie quote/scenes of The Shawshank Redemption and Remember the Titans
> Hi, I added movie quote/scenes of The Shawshank Redemption and Remember the Titans

- README.md
Add an inspirational quote with a contributing image.
> 🎇 ADD: inspirational quote

- README.md
Opening a new PR as requested by @jahway603 in #166. 
Also, since this is same as #166, I'm going ahead and closing my open PR #166
> add: new video

- README.md
Added hyperlinks to open issues and pull requests straight from readme
> Updated README.md - Added Hyper Links

- README.md
Added the book  _12 Rules for Life_ by Jordan Pederson and listed links for Goodreads and Wikipedia.
> Adding a book
